---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-mig-manager
  namespace: default
  labels:
    app: nvidia-mig-manager
spec:
  selector:
    matchLabels:
      app: nvidia-mig-manager
  template:
    metadata:
      labels:
        app: nvidia-mig-manager
    spec:
      hostPID: true
      hostIPC: true
      nodeSelector:
        nvidia.com/gpu.deploy.mig-manager: "true"
      serviceAccount: nvidia-mig-manager-service-account
      serviceAccountName: nvidia-mig-manager-service-account
      containers:
      - name: nvidia-mig-manager
        image: nvcr.io/nvidia/cloud-native/k8s-mig-manager:v0.5.4-ubi8
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CONFIG_FILE
          value: "/mig-parted-config/config.yaml"
        - name: HOST_ROOT_MOUNT
          value: "/host"
        - name: HOST_NVIDIA_DIR
          value: "/usr/local/nvidia"
        - name: HOST_MIG_MANAGER_STATE_FILE
          value: "/etc/systemd/system/nvidia-mig-manager.service.d/override.conf"
        - name: DEFAULT_GPU_CLIENTS_NAMESPACE
          value: "gpu-operator"
        - name: WITH_REBOOT
          value: "false"
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: host-root
        - mountPath: /sys
          name: host-sys
        - mountPath: /mig-parted-config
          name: mig-parted-config
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      - name: host-sys
        hostPath:
          path: /sys
          type: Directory
      - name: gpu-clients
        configMap:
          name: gpu-clients
      - name: mig-parted-config
        configMap:
          name: mig-parted-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-mig-manager-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvidia-mig-manager-role
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nvidia-mig-manager-role-binding
subjects:
  - kind: ServiceAccount
    name: nvidia-mig-manager-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: nvidia-mig-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mig-parted-config
  namespace: default
data:
  config.yaml: |
    version: v1
    mig-configs:
      all-disabled:
        - devices: all
          mig-enabled: false

      # H100-80GB, H800-80GB
      all-1g.10gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.10gb": 7

      all-1g.10gb.me:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.10gb+me": 1

      all-1g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.20gb": 4

      all-2g.20gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.20gb": 3

      all-3g.40gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "3g.40gb": 2

      all-7g.80gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.80gb": 1

      # H100 NVL, H800 NVL
      all-1g.12gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.12gb": 7

      all-1g.12gb.me:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.12gb+me": 1

      all-1g.24gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "1g.24gb": 4

      all-2g.24gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "2g.24gb": 3

      all-3g.47gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "3g.47gb": 2

      all-7g.94gb:
        - devices: all
          mig-enabled: true
          mig-devices:
            "7g.94gb": 1

      # H100-80GB, H100-NVL, H800-80GB, H800-NVL
      all-balanced:
        # H100-80GB, H800-80GB
        - device-filter: ["0x233110DE", "0x233010DE", "0x232210DE"]
          devices: all
          mig-enabled: true
          mig-devices:
            "1g.10gb": 2
            "2g.20gb": 1
            "3g.40gb": 1

        # H100 NVL, H800 NVL
        - device-filter: ["0x232110DE", "0x233A10DE"]
          devices: all
          mig-enabled: true
          mig-devices:
            "1g.12gb": 1
            "2g.24gb": 1
            "3g.47gb": 1
