run:
  timeout: 10m

linters:
  enable:
    - contextcheck
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
  disable: []

linters-settings:
  goimports:
    local-prefixes: github.com/NVIDIA/mig-parted
