# Copyright 2024 NVIDIA CORPORATION
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run this workflow on pull requests
name: build

on:
  push:
    branches:
      - main
      - release-*

jobs:
  packages:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        package:
          - deb
          - rpm
          - tarball
        ispr:
          - ${{github.event_name == 'pull_request'}}
      fail-fast: false
    runs-on: linux-${{ matrix.arch }}-cpu4
    steps:
      - uses: actions/checkout@v5
        name: Check out code
        with:
          fetch-tags: true
          fetch-depth: 1024
      - name: build ${{ matrix.package }} packages
        run: |
          sudo apt-get install -y coreutils build-essential sed git bash make
          echo "Building packages"
          make -f deployments/systemd/packages/Makefile ${{ matrix.package }}-${{ matrix.arch }}
      - name: 'Upload Artifacts'
        uses: actions/upload-artifact@v5
        with:
          compression-level: 0
          name: mig-parted-${{ matrix.package }}-${{ matrix.arch }}-${{ github.run_id }}
          path: ${{ github.workspace }}/dist/*
